version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: compliance_postgres
    restart: always
    environment:
      POSTGRES_USER: compliance_user
      POSTGRES_PASSWORD: compliance_pass
      POSTGRES_DB: compliance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: compliance_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"  # management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  redis:
    image: redis:7
    container_name: compliance_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
